import {Fragment} from 'react';
import type {Locale} from '../content/home';
import projects from '../content/projects.json';
import {stories,type StoryId} from '../lib/stories';
import {SiteShell,pagePath,Arrow} from './site-shell';
// The authored Markdown subset is headings, paragraphs, links and lists. React escapes text.
function inline(text:string) {return text.split(/(\[[^\]]+\]\(https?:\/\/[^)]+\)|`[^`]+`)/g).map((part,i)=>{const link=part.match(/^\[([^\]]+)\]\((https?:\/\/[^)]+)\)$/);return link?<a key={i} href={link[2]}>{link[1]}</a>:part.startsWith('`')?<code key={i}>{part.slice(1,-1)}</code>:<Fragment key={i}>{part}</Fragment>})}
export default function ProjectStory({locale,id}:{locale:Locale;id:StoryId}) {
 const [heading,lead,...blocks]=stories[locale][id].trim().split(/\n\s*\n/);const p=projects.find(p=>p.id===id)!;const fr=locale==='fr';
 return <SiteShell locale={locale} path={'projects/'+id+'/'}><article className="story"><header className="page-intro"><a className="back-link" href={pagePath(locale,'projects/')}>{fr?'← Tous les projets':'← All projects'}</a><p className="eyebrow">{p.tags.join(' · ')} · {p.year}</p><h1>{heading.replace(/^# /,'')}</h1><p className="intro">{lead}</p></header><div className="story-layout"><aside className="story-aside"><p className="eyebrow">{fr?'Ma contribution':'My contribution'}</p><p>{p[locale].role}</p><p className="project-status">{p[locale].status}</p><a className="text-link" href={p.repo}>GitHub <Arrow/></a></aside><div className="prose">{blocks.map((block,i)=>block.startsWith('## ')?<h2 key={i}>{block.slice(3)}</h2>:block.startsWith('- ')?<ul key={i}>{block.split('\n').map((line,j)=><li key={j}>{inline(line.slice(2))}</li>)}</ul>:<p key={i}>{inline(block.replace(/\n/g,' '))}</p>)}</div></div>{id==='droit-de-retard'&&<figure className="story-figure"><a href="/images/droit-de-retard.png"><img src="/images/droit-de-retard.png" width="1440" height="1180" loading="lazy" alt={fr?'Interface de démonstration Droit de Retard : document de vol et trace de l’analyse.':'Droit de Retard demo interface: flight document and analysis trace.'}/></a><figcaption>{fr?'Interface de démonstration du dépôt Droit de Retard.':'Demo interface from the Droit de Retard repository.'} <a href="/images/droit-de-retard.png">{fr?'Ouvrir l’image en taille réelle':'Open full-size image'} ↗</a> · <a href="https://github.com/Wesper-Dev/droit-de-retard/blob/main/docs/images/interface.png">{fr?'Source et crédit':'Source and credit'}</a></figcaption></figure>}<nav className="story-next" aria-label={fr?'Autres récits':'More stories'}>{projects.filter(p=>p.story&&p.id!==id).map(p=><a key={p.id} href={pagePath(locale,'projects/'+p.id+'/')}>{p.name} <Arrow/></a>)}</nav></article></SiteShell>;
}
